### ISSUE TITLE
Scene Status Data is missing

### ISSUE THREAD

**Issue by MathieuChillon** [ViveSoftware/Bouncing-Duel-MR#1]
Hi!

When trying to play this demo, I encountered some errors.

Notably, the text asset *Scene Status Data* is missing in the prefab *ScenePerception*. Without this asset, the code tries to use this data and generates errors. As a workaround, it is possible on the script *MRRoomManager* to set *scenePerceptionHelper.IsUseSavedSceneData* to false on line 67. This works but a proper fix would be appreciated.

Thanks in advance!

Mathieu

**Comment by YenYaoHan** [comment]
Hi, @MathieuChillon 

Thanks for your support and suggestion!
Regarding the missing file, it’s a fake data to describe the room mesh in Editor mode. 
Due to company policy, we can't release it in the project, but don’t worry, it won’t affect the app’s process. 
You can safely ignore it.
We’ve already fixed the issue in the latest commit. 
Just make sure your project plugins and environment are full completed, 
build the .apk directly onto your devices, and enjoy the game.

Cheers!
